In [1]:
import numpy as np

In [2]:
l1 =[1,2,3,4,5]

In [6]:
n1=np.array(l1)

In [7]:
n1

array([1, 2, 3, 4, 5])

In [9]:
type(n1)

numpy.ndarray

In [12]:
n2=np.array([[1,2,3,4],[4,3,2,1]])

In [13]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [20]:
n3=np.zeros((10,10))

In [21]:
type(n3)

numpy.ndarray

In [22]:
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
n4 = np.full((3,3),55)

In [24]:
n4

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])